#'  MODIStsp_launcher
#' @description Utility to launch MODIStsp from batch/bash file
#' @details This script is used from the batch launchers MODIStsp.sh and MODIStsp.bat to launch MODIStsp using Rscript
#'  (do not run it; launch from MODIStsp.sh or MODIStsp.bat).
#'  It reads three external parameters (respectively "MODIStsp_dir", "gui" and "options_file"; see MODIStsp() for details)
#'  storing them in the variable "Args"; the first one is automatically generated by the batch/bash scripts; others are optional.
##' @param MODIStsp_dir main directory of the local installation of the tool(if not gived, it is automatically retrieved, but this works only if the function is launched from here!)
##' @param gui logical parameter (TRUE: the GUI is opened before processing; FALSE: the saved parameters are directly passed)
##' @param options_file settings (optional): full path of the RData file containing the processing options (default: Previous.RData in subdir Previous);
#' @return NULL
#'
#' @author Lorenzo Busetto, phD (2014-2015)
#' email: busetto.l@@irea.cnr.it
#' Luigi Ranghetti, phD (2015)
#' license GPL 3.0


Args <- commandArgs(TRUE)

MODIStsp_dir <- Args[1]
gui = if (length(Args)>=2) as.logical(Args[2]) else TRUE
options_file = if (length(Args)>=3) {if (Args[3]=="") NULL else Args[3]} else NULL
if (length(Args)>=3) {
	load (options_file)
	log_dir = file.path(general_opts$out_folder,'Log')
} else {
	log_dir = file.path(MODIStsp_dir,'Log')
}
dir.create(log_dir,showWarnings=FALSE)
outFile <- file.path(log_dir,paste0('MODIStsp_',strftime(Sys.time(),'%y%m%d_%H%M%S'),".Rout")) # directory to store the Log

require(MODIStsp)
MODIStsp_dir = system.file(package = 'MODIStsp')

sink(outFile, split = TRUE, type = c("output"))
output = MODIStsp(gui=gui, options_file=options_file)
sink(type = c("output"))
